CREATE DATABASE IF NOT EXISTS succulent_monitoring;
USE succulent_monitoring;

CREATE TABLE IF NOT EXISTS users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  role ENUM('admin','user') NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP)

CREATE TABLE IF NOT EXISTS humidity (
  humidity_id INT AUTO_INCREMENT PRIMARY KEY,
  humidity_percent DECIMAL(5,2) NOT NULL,
  status VARCHAR(20) NOT NULL,
  recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP)
